In [21]:
import pandas as pd

In [49]:
# import column dict for colname transform
coldict_file = "ASR_column_dict.csv"
col_df = pd.read_csv(coldict_file)

In [48]:
# import ASR data
asr_2017_file = "ASR_2017.csv"
asr_2017 = pd.read_csv(asr_2017_file)
asr_2017.rename(columns = dict(
    zip(col_df['Source Field Name']
        , col_df['Destination Field Name']
       )
    )
               ,inplace=True)
asr_2017.head()

/var/folders/54/fvj8xtl92fl25v_rfc4twzgw0000gn/T/ipykernel_88308/1179045898.py:3: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  asr_2017 = pd.read_csv(asr_2017_file)

,Property Location,Assessor Neighborhood Code,Block and Lot,Volume Number,Property Class Code,Year Property Built,Number of Bathrooms,Number of Bedrooms,Number of Rooms,Number of Stories,...,Exemption Code,Status Code,Misc Exemption Value,Homeowner Exemption Value,Closed Roll Year,Current Sales Date,Assessed Fixtures Value,Assessed Improvement Value,Assessed Land Value,Assessed Personal Property Value
0,0000 0000 0000,08H,0001 001,1,G,1900,0,0,0,0,...,NaN,N,0,0,17,0,0,0,0,0
1,0000 0000 0000,08H,0002 001,1,G,1900,0,0,0,0,...,NaN,N,0,0,17,0,0,0,0,0
2,0000 0000 0000,08H,0004 002,1,VCI,0,0,0,0,0,...,NaN,N,0,0,17,0,0,0,0,0
3,0000 0286 JEFFERSON ST0000,08H,0005 001,1,G,1900,0,0,0,0,...,NaN,N,0,0,17,0,0,0,0,0
4,0000 0000 0000,08H,0006 001,1,G,1900,0,0,0,0,...,NaN,N,0,0,17,0,0,0,0,0